### ISSUE TITLE
"None" output

### ISSUE THREAD

**Issue by captainmorgan** [svvitale/nxppy#15]
Using your second code example, when I touch a card to the nfc-explore device, the output is "None".

I've tested with several cards, including the MIFARE ultralight supplied with the unit.

I did install nxppy using pip.

**Comment by svvitale** [comment]
Hi @captainmorgan, I know this issue was filed a long LONG time ago, and my apologies for not responding sooner.  I have done a fresh install today on my Raspberry Pi and I'm not able to observe this issue.  Because of the age (I'm not sure you're even still experimenting with this), I'm going to close the ticket.  If you're still having issues and would like some help, I'd be happy to reopen it.
